### ISSUE TITLE
Panel crash with invalid configuration

### ISSUE THREAD

**Issue by xkilian** [andymchugh/andrewbmchugh-flow-panel#107] opened 2024-09-06 14:31 UTC
Defining fillColour and fillColourCompund in the same cell definition will crash the Flow panel.

`cells:`
`  station1:`
`    dataRef: "station1"`
`    label:`
`      units: "none"`
`    fillColor:`
`      thresholdsRef: "station-threshold"`
`    fillColorCompound:	  `
`      function: "max"`

**Comment by andymchugh** [comment] 2024-09-06 18:01
The docs say that if you define both the fillColor gets prepended to the compound array https://github.com/andymchugh/andrewbmchugh-flow-panel/blob/main/yaml_defs/panelConfig.yaml#L402

and there is an example of that in the provisioning tests here: https://github.com/andymchugh/andrewbmchugh-flow-panel/blob/main/provisioning/dashboardData/compoundColor.yaml#L84

So I believe this works fine. Looking at your data above you do appear to have an indentation problem. yaml is very sensitive to indentation. You fillColorCompound is indented at a level between station1 and fillColor. That's the most likely cause of your problem. Can you check?

**Comment by xkilian** [comment] 2024-09-06 21:05
Corrected the indentation, still crashes.

`colors:`
`  red: "#FF0000"`
`  orange: "#FFBF00"`
`  green: "#00FF00"`

`anchorLinks:`
`  - threshold: &station-threshold`
`      - {color: "red", level: 0, order: 2}`
`      - {color: "green", level: 1, order: 0}`
`gradientMode: "none"`
`cellIdPreamble: "cell-"`
`cellLabelDecimalPoints: null`
`cells:`
`  2S22:`
`    dataRef: "2S22"`
`    fillColor:`
`      thresholdsRef: *station-threshold`
`    fillColorCompound:`
`      function: "max"`

**Comment by andymchugh** [comment] 2024-09-11 22:53
Ah ok. So the problem is the fillColor is defined and a fillColorCompound section is defined but with no colors array so the compound function has nothing to compound. I've landed a change on main so this combination doesn't throw out and instead it just uses fillColor.

**Comment by andymchugh** [comment] 2024-09-25 17:30
this is now fixed on version 1.16.5

**Closed by andymchugh** 2024-09-25 17:30 UTC
